# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - 'dependencies'
      - 'ignore-for-release'
    groups:
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      turbo:
        patterns:
          - "turbo"
          - "@turbo/*"
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - 'dependencies'
      - 'ignore-for-release'
