name: "Checks"

on:
  pull_request:
    branches:
      - main

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changed:
    runs-on: ubuntu-22.04
    outputs:
      frontend: ${{ steps.needs.outputs.frontend }}
      docs: ${{ steps.needs.outputs.docs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Paths Changes Filter
        uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            frontend:
              - 'apps/frontend/**/*'
              - 'package.json'
            docs:
              - 'apps/docs/**/*'
              - 'package.json'
      - name: Output Needs
        id: needs
        run: |
          echo "frontend=${{ steps.changes.outputs.frontend == 'true' }}" >> $GITHUB_OUTPUT
          echo "docs=${{ steps.changes.outputs.docs == 'true' }}" >> $GITHUB_OUTPUT

  check-frontend:
    runs-on: ubuntu-22.04
    needs: changed
    if: needs.changed.outputs.frontend == 'true'
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1.1.1

      - name: Install deps (with cache)
        run: bun install --filter=frontend --frozen-lockfile

      - name: Build
        run: bun run build --filter=frontend

  check-docs:
    runs-on: ubuntu-22.04
    needs: changed
    if: needs.changed.outputs.docs == 'true'
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1.1.1

      - name: Install deps (with cache)
        run: bun install --filter=docs --frozen-lockfile

      - name: Build
        run: bun run build --filter=docs
