name: "Preview"

on:
  pull_request:
    branches:
      - main

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changed:
    runs-on: ubuntu-22.04

    outputs:
      frontend: ${{ steps.needs.outputs.frontend }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Paths Changes Filter
        uses: dorny/paths-filter@v3.0.1
        id: changes
        with:
          filters: |
            frontend:
              - 'apps/frontend/**/*'
              - 'package.json'
      - name: Output Needs
        id: needs
        run: |
          echo "frontend=${{ env.IS_DISPATCH == 'true' || steps.changes.outputs.frontend == 'true' }}" >> $GITHUB_OUTPUT

  preview-frontend:
    runs-on: ubuntu-22.04
    needs: changed
    if: needs.changed.outputs.frontend == 'true'

    permissions:
      contents: read
      deployments: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1.8.1
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1.1.1

      - name: Install deps (with cache)
        run: bun install --filter=frontend

      - name: Build
        run: bun run build --filter=frontend...

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        id: cloudflare-pages
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: nito
          directory: ./apps/frontend/dist
          gitHubToken: ${{ steps.app-token.outputs.token }}
          branch: preview

      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@v10.0.0
        with:
          gitHubAccessToken: ${{ steps.app-token.outputs.token }}
          locale: ja
          prCommentEnabled: true
          urls: ${{ steps.cloudflare-pages.outputs.url }}
